### ISSUE TITLE
Issue with file

### ISSUE THREAD

**Issue by ndbellew** [MatthewDvorak/beginning#1]
File isn't running properly may need update.

**Comment by MatthewDvorak** [comment]
What issue are you running into?

**Comment by sdwalsh** [comment]
Are you having trouble compiling the typescript or running the output on node?

we're using node v17.1.0

Run the following when you clone the repository:
`yarn install`
`yarn run dev`

If you want to change the input on the current version of master, you'll need to change the variable `dayOneInputAoc` in `day-one-input-aoc.ts`

I have a PR open to change the structure a bit which will expose HTTP endpoints for each day:

- #2

(The goal eventually being to build a small React project around it)

**Comment by ndbellew** [comment]
Yeah that worked.
